INSERT INTO menu (restaurant_id, item_name, price, category, image, rating, isAvailable, description) VALUES
-- Group A
(1, 'Margherita Pizza', 299, 'Main', 'margherita.jpg', 4.5, 1, 'Classic Italian pizza with fresh basil and mozzarella.'),
(1, 'Pepperoni Pizza', 349, 'Main', 'peppi.jpg', 4.7, 1, 'Spicy pepperoni on a bed of melted mozzarella and tomato sauce.'),
(1, 'Garlic Breadsticks', 149, 'Starter', 'garlic.jpg', 4.3, 1, 'Freshly baked breadsticks brushed with garlic butter and herbs.'),
(1, 'Tiramisu', 199, 'Dessert', 'chocolate.jpg', 4.8, 1, 'Traditional Italian coffee-flavored dessert.'),
(1, 'Iced Tea', 99, 'Beverage', 'coke.jpg', 4.2, 1, 'Refreshing chilled tea with a hint of lemon.'),
(2, 'Butter Chicken', 399, 'Main', 'butter.jpg', 4.9, 1, 'Tender chicken simmered in a rich and creamy tomato gravy.'),
(2, 'Mutton Biryani', 499, 'Main', 'jeera.jpg', 4.8, 1, 'Aromatic basmati rice cooked with succulent pieces of mutton and spices.'),
(2, 'Paneer Tikka', 249, 'Starter', 'masala.jpg', 4.6, 1, 'Cubes of paneer marinated in spices and grilled to perfection.'),
(2, 'Gulab Jamun', 129, 'Dessert', 'lava.jpg', 4.7, 1, 'Soft and spongy milk solids soaked in sugar syrup.'),
(2, 'Mango Lassi', 149, 'Beverage', 'coke.jpg', 4.8, 1, 'Sweet and creamy yogurt-based drink flavored with ripe mangoes.'),
(3, 'Whopper', 249, 'Main', 'chickenwhopper.jpg', 4.5, 1, 'Flame-grilled signature patty topped with fresh tomatoes, lettuce, and mayo.'),
(3, 'Chicken Royale', 229, 'Main', 'vegwhopper.jpg', 4.4, 1, 'Crispy chicken patty with lettuce and creamy mayonnaise.'),
(3, 'French Fries', 119, 'Starter', 'french.jpg', 4.6, 1, 'Golden, crispy potato fries lightly salted.'),
(3, 'Chocolate Shake', 179, 'Beverage', 'chocolate.jpg', 4.3, 1, 'Thick and creamy chocolate milkshake.'),
(3, 'Onion Rings', 139, 'Starter', 'nuggets.jpg', 4.2, 1, 'Crispy, golden-fried onion rings.'),

-- Group B
(4, 'Butter Chicken', 299.00, 'Mains', 'butter.jpg', 4.8, 1, 'Rich and creamy Punjabi chicken curry cooked in tomato and butter sauce.'),
(4, 'Paneer Tikka Masala', 249.00, 'Mains', 'masala.jpg', 4.6, 1, 'Marinated paneer chunks grilled and served in a spiced gravy.'),
(4, 'Dal Makhani', 199.00, 'Mains', 'dal.jpg', 4.7, 1, 'Slow-cooked black lentils with cream and butter.'),
(4, 'Garlic Naan', 49.00, 'Breads', 'roti.jpg', 4.5, 1, 'Traditional Indian flatbread topped with minced garlic and baked in a tandoor.'),
(4, 'Sweet Lassi', 99.00, 'Beverages', 'coke.jpg', 4.6, 1, 'Refreshing and sweet yogurt-based traditional Punjabi drink.'),
(5, 'Masala Dosa', 149.00, 'Mains', 'masala.jpg', 4.7, 1, 'Crispy rice and lentil crepe stuffed with spiced potato filling.'),
(5, 'Idli Sambar', 99.00, 'Starters', 'dal.jpg', 4.5, 1, 'Steamed rice cakes served with a flavorful lentil and vegetable stew.'),
(5, 'Medu Vada', 109.00, 'Starters', 'nuggets.jpg', 4.4, 1, 'Deep-fried lentil savory donuts, crispy outside and soft inside.'),
(5, 'Chicken Chettinad', 279.00, 'Mains', 'butter.jpg', 4.8, 1, 'Spicy and aromatic South Indian chicken curry made with roasted spices.'),
(5, 'Filter Coffee', 59.00, 'Beverages', 'coke.jpg', 4.9, 1, 'Strong and frothy traditional South Indian coffee.'),
(6, 'Tandoori Chicken', 349.00, 'Starters', 'chicken.jpg', 4.8, 1, 'Classic bone-in chicken marinated in yogurt and spices, roasted in a clay oven.'),
(6, 'Seekh Kebab', 299.00, 'Starters', 'nuggets.jpg', 4.6, 1, 'Minced lamb mixed with aromatic spices, skewered and grilled.'),
(6, 'Chicken Tikka', 289.00, 'Starters', 'chicken.jpg', 4.7, 1, 'Boneless chicken pieces marinated in spices and grilled to perfection.'),
(6, 'Mutton Rogan Josh', 399.00, 'Mains', 'mutton_rogan_josh_1783008774180.png', 4.9, 1, 'Tender mutton cooked in a rich, flavorful North Indian spiced gravy.'),
(6, 'Gulab Jamun', 120.00, 'Desserts', 'lava.jpg', 4.8, 1, 'Soft milk dough balls deep-fried and soaked in cardamom-flavored sugar syrup.'),

-- Group C (Using new generated images)
(7, 'Shahi Paneer', 249, 'Main Course', 'shahi_paneer_1783008761364.png', 4.6, 1, 'Rich and creamy cottage cheese curry prepared with dry fruits, saffron, and aromatic spices.'),
(7, 'Mutton Rogan Josh', 399, 'Main Course', 'mutton_rogan_josh_1783008774180.png', 4.8, 1, 'Classic slow-cooked tender lamb in a flavorful rich, red gravy.'),
(7, 'Murgh Makhani', 349, 'Main Course', 'murgh_makhani_1783008784396.png', 4.7, 1, 'Butter chicken cooked to perfection in a creamy tomato gravy with a touch of fenugreek.'),
(7, 'Nawabi Biryani', 299, 'Main Course', 'nawabi_biryani_1783008794437.png', 4.5, 1, 'Aromatic basmati rice cooked with succulent pieces of meat, saffron, and traditional Awadhi spices.'),
(7, 'Shahi Tukda', 149, 'Dessert', 'shahi_tukda_1783008815589.png', 4.6, 1, 'A royal dessert made with fried bread slices soaked in saffron-infused milk and topped with nuts.'),
(8, 'Pani Puri', 49, 'Starter', 'pani_puri_1783008826694.png', 4.8, 1, 'Crispy hollow puris filled with spicy, tangy mint water and a savory potato mix.'),
(8, 'Aloo Tikki Chaat', 79, 'Starter', 'aloo_tikki_chaat_1783008875523.png', 4.5, 1, 'Golden fried potato patties topped with sweet and spicy chutneys, yogurt, and crunchy sev.'),
(8, 'Pav Bhaji', 120, 'Main Course', 'pav_bhaji_1783008886428.png', 4.7, 1, 'Spicy and buttery mashed vegetable curry served with soft, toasted buns.'),
(8, 'Vada Pav', 30, 'Starter', 'vada_pav_1783008854804.png', 4.6, 1, 'Mumbai famous street food featuring a spicy potato fritter served in a soft bun with chutneys.'),
(8, 'Samosa Chaat', 60, 'Starter', 'nuggets.jpg', 4.4, 1, 'Crushed crispy samosas mixed with chole, yogurt, and a blend of sweet and spicy chutneys.'),
(9, 'Maharaja Thali', 499, 'Main Course', 'jeera.jpg', 4.9, 1, 'A grand feast featuring an elaborate spread of curries, bread, rice, appetizers, and desserts on a single platter.'),
(9, 'Gujarati Thali', 299, 'Main Course', 'dal.jpg', 4.6, 1, 'A traditional sweet and savory platter consisting of dal, kadhi, fresh vegetables, rotis, and traditional sweets.'),
(9, 'Punjabi Chole Bhature', 199, 'Main Course', 'masala.jpg', 4.7, 1, 'Spicy, rich chickpea curry served with fluffy, deep-fried bhature and tangy pickles.'),
(9, 'Sweet Lassi', 80, 'Beverage', 'coke.jpg', 4.8, 1, 'Traditional, refreshing yogurt-based drink churned to creamy perfection with a hint of cardamom.'),
(9, 'Gulab Jamun', 60, 'Dessert', 'lava.jpg', 4.7, 1, 'Soft, deep-fried milk dumplings soaked in a warm, fragrant sugar syrup.'),

-- Group D
(10, 'Classic Cheeseburger', 199, 'Burgers', 'vegwhopper.jpg', 4.5, 1, 'Juicy beef patty with melted cheese, lettuce, and tomato on a toasted bun.'),
(10, 'Spicy Chicken Sandwich', 249, 'Burgers', 'chickenwhopper.jpg', 4.6, 1, 'Crispy fried chicken breast with spicy mayo and pickles.'),
(10, 'Loaded Fries', 149, 'Starters', 'french.jpg', 4.3, 1, 'Crispy french fries topped with melted cheese and jalapeños.'),
(10, 'Onion Rings', 129, 'Starters', 'nuggets.jpg', 4.4, 1, 'Golden, crispy battered onion rings.'),
(10, 'Chocolate Milkshake', 179, 'Beverages', 'chocolate.jpg', 4.7, 1, 'Rich and creamy chocolate milkshake topped with whipped cream.'),
(11, 'Quinoa Buddha Bowl', 299, 'Mains', 'jeera.jpg', 4.8, 1, 'Healthy bowl with quinoa, roasted chickpeas, avocado, and tahini dressing.'),
(11, 'Avocado Toast', 249, 'Starters', 'garlic.jpg', 4.6, 1, 'Mashed avocado on toasted sourdough with cherry tomatoes and seeds.'),
(11, 'Kale Caesar Salad', 279, 'Salads', 'veg.jpg', 4.5, 1, 'Fresh kale tossed in vegan Caesar dressing with croutons.'),
(11, 'Green Detox Smoothie', 199, 'Beverages', 'coke.jpg', 4.7, 1, 'Refreshing blend of spinach, green apple, cucumber, and ginger.'),
(11, 'Vegan Wrap', 229, 'Mains', 'vegwhopper.jpg', 4.4, 1, 'Whole wheat wrap filled with hummus, falafel, and mixed greens.');
